app/urls.py
from django.urls import path
from app.views import logic, HomePageView

app_name = 'app'

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('logic/', logic, name='logic'),
]

webim/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('', include('app.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
from django.db import models


class Number(models.Model):
    value = models.SmallIntegerField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.value)

    class Meta:
        verbose_name = 'Number'
        verbose_name_plural = 'Numbers'

app/views.py
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView
from django.shortcuts import render
from app.redis_server import redis_instance


# from app.management.commands.num_gen import singleton


class HomePageView(TemplateView):
    template_name = "app/main.html"


@login_required(login_url='')
def logic(request):
    if request.method == 'GET':
        rand_num = redis_instance.get('rand_num')
        return render(request, 'app/logic.html',
                      context={'random_number': rand_num})

    return render(request, 'app/logic.html')

# def system(request):
#     return render(request, 'app/system.html')

templates/app/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
          integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    {% block title %}
        <title>Base</title>
    {% endblock %}
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'app:home' %}">Webim</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
            aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
            <a class="nav-link active" href="{% url 'app:home' %}">Home <span class="sr-only">(current)</span></a>
            <a class="nav-link active" href="{% url 'app:logic' %}">Logic <span class="sr-only">(current)</span></a>
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'account_logout' %}">Logout</a>
                </li>
            {% endif %}

        </div>

    </div>
</nav>

{% block content %}
    No content
{% endblock %}
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
</script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous">

</script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
        integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
        crossorigin="anonymous"></script>
<script src="{% static 'js/main.js' %}"></script>

</body>
</html>

templates/app/logic.html
{% extends 'app/base.html' %}
{% load static %}
{% load is_number_tag %}
{% block title %}
    <title>Logic</title>
{% endblock %}
{% block content %}
    <div class="container text-dark mt-5">
        <div class="row justify-content-md-center">
            <div class="col-md-5 p-3">
                <div class="alert alert-success d-flex justify-content-center" role="alert">
                    <h1>
                        <div class="random_number" id="random_number">
                            {{ random_number }}
                        </div>
                    </h1>
                </div>
            </div>
        </div>
    </div>
    {#    <script src="https://cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>#}
    {#    <script src="https://cdnjs.cloudflare.com/ajax/libs/justgage/1.1.0/justgage.js"></script>#}
    <script>
    function connect() {
        const systemSocket = new WebSocket(`ws://${window.location.host}/ws/logic/`);
        systemSocket.onopen = () =>
            systemSocket.send(JSON.stringify({"message": 'Sending message to server'}));

        systemSocket.onmessage = function (e) {
            const data = JSON.parse(e.data);
            {#rand_num.refresh(data.random_number);#}
            document.getElementById("random_number").textContent = data.random_number;
        };
        systemSocket.onclose = function (e) {
            console.error('Chat socket closed');
            setTimeout(() => connect(), 1000);
        };
    }
    connect();
    </script>
{% endblock %}

templates/app/main.html
{% extends 'app/base.html' %}
{% block title %}
    {{ page }}
{% endblock %}
{% block content %}
    {% if user.is_authenticated %}
        <h1> Hello, {{ user.username }}</h1>
    {% else %}
        <a class="nav-link" href="{% url 'github_login' %}">Авторизоваться</a>
    {% endif %}
{% endblock %}